package farmacia.hibernate.modelo;
// Generated Oct 25, 2018 3:35:34 PM by Hibernate Tools 4.3.1



/**
 * Boletadetalle generated by hbm2java
 */
public class Boletadetalle  implements java.io.Serializable {


     private Integer idboletadetalle;
     private Boletacabecera boletacabecera;
     private Producto producto;
     private double cantidad;
     private double subtotal;
     private boolean status;

    public Boletadetalle() {
    }

    public Boletadetalle(Boletacabecera boletacabecera, Producto producto, double cantidad, double subtotal, boolean status) {
       this.boletacabecera = boletacabecera;
       this.producto = producto;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
       this.status = status;
    }
   
    public Integer getIdboletadetalle() {
        return this.idboletadetalle;
    }
    
    public void setIdboletadetalle(Integer idboletadetalle) {
        this.idboletadetalle = idboletadetalle;
    }
    public Boletacabecera getBoletacabecera() {
        return this.boletacabecera;
    }
    
    public void setBoletacabecera(Boletacabecera boletacabecera) {
        this.boletacabecera = boletacabecera;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


