package farmacia.hibernate.modelo;
// Generated Oct 25, 2018 3:35:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Boletacabecera generated by hbm2java
 */
public class Boletacabecera  implements java.io.Serializable {


     private Integer idboletacabecera;
     private Empleado empleado;
     private Personacliente personacliente;
     private String correlativoboleta;
     private String numeroboleta;
     private Date fechaemisionboleta;
     private boolean status;
     private Set boletadetalles = new HashSet(0);

    public Boletacabecera() {
    }

	
    public Boletacabecera(Empleado empleado, Personacliente personacliente, String correlativoboleta, String numeroboleta, Date fechaemisionboleta, boolean status) {
        this.empleado = empleado;
        this.personacliente = personacliente;
        this.correlativoboleta = correlativoboleta;
        this.numeroboleta = numeroboleta;
        this.fechaemisionboleta = fechaemisionboleta;
        this.status = status;
    }
    public Boletacabecera(Empleado empleado, Personacliente personacliente, String correlativoboleta, String numeroboleta, Date fechaemisionboleta, boolean status, Set boletadetalles) {
       this.empleado = empleado;
       this.personacliente = personacliente;
       this.correlativoboleta = correlativoboleta;
       this.numeroboleta = numeroboleta;
       this.fechaemisionboleta = fechaemisionboleta;
       this.status = status;
       this.boletadetalles = boletadetalles;
    }
   
    public Integer getIdboletacabecera() {
        return this.idboletacabecera;
    }
    
    public void setIdboletacabecera(Integer idboletacabecera) {
        this.idboletacabecera = idboletacabecera;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Personacliente getPersonacliente() {
        return this.personacliente;
    }
    
    public void setPersonacliente(Personacliente personacliente) {
        this.personacliente = personacliente;
    }
    public String getCorrelativoboleta() {
        return this.correlativoboleta;
    }
    
    public void setCorrelativoboleta(String correlativoboleta) {
        this.correlativoboleta = correlativoboleta;
    }
    public String getNumeroboleta() {
        return this.numeroboleta;
    }
    
    public void setNumeroboleta(String numeroboleta) {
        this.numeroboleta = numeroboleta;
    }
    public Date getFechaemisionboleta() {
        return this.fechaemisionboleta;
    }
    
    public void setFechaemisionboleta(Date fechaemisionboleta) {
        this.fechaemisionboleta = fechaemisionboleta;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getBoletadetalles() {
        return this.boletadetalles;
    }
    
    public void setBoletadetalles(Set boletadetalles) {
        this.boletadetalles = boletadetalles;
    }


    public static void main(String[] args) {
        Integer i = 123;
        System.out.println(i);
    }

}


