package farmacia.hibernate.modelo;
// Generated Oct 25, 2018 3:35:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Descuento generated by hbm2java
 */
public class Descuento  implements java.io.Serializable {


     private Integer iddescuento;
     private String nombredescuento;
     private String condicion;
     private double porcentaje;
     private String descripciondescuento;
     private boolean status;
     private Set productodescuentos = new HashSet(0);

    public Descuento() {
    }

	
    public Descuento(String nombredescuento, String condicion, double porcentaje, boolean status) {
        this.nombredescuento = nombredescuento;
        this.condicion = condicion;
        this.porcentaje = porcentaje;
        this.status = status;
    }
    public Descuento(String nombredescuento, String condicion, double porcentaje, String descripciondescuento, boolean status, Set productodescuentos) {
       this.nombredescuento = nombredescuento;
       this.condicion = condicion;
       this.porcentaje = porcentaje;
       this.descripciondescuento = descripciondescuento;
       this.status = status;
       this.productodescuentos = productodescuentos;
    }
   
    public Integer getIddescuento() {
        return this.iddescuento;
    }
    
    public void setIddescuento(Integer iddescuento) {
        this.iddescuento = iddescuento;
    }
    public String getNombredescuento() {
        return this.nombredescuento;
    }
    
    public void setNombredescuento(String nombredescuento) {
        this.nombredescuento = nombredescuento;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(double porcentaje) {
        this.porcentaje = porcentaje;
    }
    public String getDescripciondescuento() {
        return this.descripciondescuento;
    }
    
    public void setDescripciondescuento(String descripciondescuento) {
        this.descripciondescuento = descripciondescuento;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getProductodescuentos() {
        return this.productodescuentos;
    }
    
    public void setProductodescuentos(Set productodescuentos) {
        this.productodescuentos = productodescuentos;
    }




}


