package farmacia.hibernate.modelo;
// Generated Oct 25, 2018 3:35:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idempleado;
     private Persona persona;
     private Tipotrabajador tipotrabajador;
     private String login;
     private String password;
     private Date fechaalta;
     private boolean status;
     private Set facturacabeceras = new HashSet(0);
     private Set boletacabeceras = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(Persona persona, Tipotrabajador tipotrabajador, String login, String password, boolean status) {
        this.persona = persona;
        this.tipotrabajador = tipotrabajador;
        this.login = login;
        this.password = password;
        this.status = status;
    }
    public Empleado(Persona persona, Tipotrabajador tipotrabajador, String login, String password, Date fechaalta, boolean status, Set facturacabeceras, Set boletacabeceras) {
       this.persona = persona;
       this.tipotrabajador = tipotrabajador;
       this.login = login;
       this.password = password;
       this.fechaalta = fechaalta;
       this.status = status;
       this.facturacabeceras = facturacabeceras;
       this.boletacabeceras = boletacabeceras;
    }
   
    public Integer getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(Integer idempleado) {
        this.idempleado = idempleado;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Tipotrabajador getTipotrabajador() {
        return this.tipotrabajador;
    }
    
    public void setTipotrabajador(Tipotrabajador tipotrabajador) {
        this.tipotrabajador = tipotrabajador;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFechaalta() {
        return this.fechaalta;
    }
    
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getFacturacabeceras() {
        return this.facturacabeceras;
    }
    
    public void setFacturacabeceras(Set facturacabeceras) {
        this.facturacabeceras = facturacabeceras;
    }
    public Set getBoletacabeceras() {
        return this.boletacabeceras;
    }
    
    public void setBoletacabeceras(Set boletacabeceras) {
        this.boletacabeceras = boletacabeceras;
    }




}


