package farmacia.hibernate.modelo;
// Generated Oct 25, 2018 3:35:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer idempresa;
     private String rucempresa;
     private String razonsocial;
     private String telefono;
     private String direccion;
     private boolean status;
     private Set empresaclientes = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String rucempresa, String razonsocial, String telefono, String direccion, boolean status) {
        this.rucempresa = rucempresa;
        this.razonsocial = razonsocial;
        this.telefono = telefono;
        this.direccion = direccion;
        this.status = status;
    }
    public Empresa(String rucempresa, String razonsocial, String telefono, String direccion, boolean status, Set empresaclientes) {
       this.rucempresa = rucempresa;
       this.razonsocial = razonsocial;
       this.telefono = telefono;
       this.direccion = direccion;
       this.status = status;
       this.empresaclientes = empresaclientes;
    }
   
    public Integer getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(Integer idempresa) {
        this.idempresa = idempresa;
    }
    public String getRucempresa() {
        return this.rucempresa;
    }
    
    public void setRucempresa(String rucempresa) {
        this.rucempresa = rucempresa;
    }
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getEmpresaclientes() {
        return this.empresaclientes;
    }
    
    public void setEmpresaclientes(Set empresaclientes) {
        this.empresaclientes = empresaclientes;
    }




}


