package farmacia.hibernate.modelo;
// Generated Oct 25, 2018 3:35:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facturacabecera generated by hbm2java
 */
public class Facturacabecera  implements java.io.Serializable {


     private Integer idfacturacabecera;
     private Empleado empleado;
     private Empresacliente empresacliente;
     private String correlativofactura;
     private String numerofactura;
     private Date fechaemisionfactura;
     private boolean status;
     private Set facturadetalles = new HashSet(0);

    public Facturacabecera() {
    }

	
    public Facturacabecera(Empleado empleado, Empresacliente empresacliente, String correlativofactura, String numerofactura, Date fechaemisionfactura, boolean status) {
        this.empleado = empleado;
        this.empresacliente = empresacliente;
        this.correlativofactura = correlativofactura;
        this.numerofactura = numerofactura;
        this.fechaemisionfactura = fechaemisionfactura;
        this.status = status;
    }
    public Facturacabecera(Empleado empleado, Empresacliente empresacliente, String correlativofactura, String numerofactura, Date fechaemisionfactura, boolean status, Set facturadetalles) {
       this.empleado = empleado;
       this.empresacliente = empresacliente;
       this.correlativofactura = correlativofactura;
       this.numerofactura = numerofactura;
       this.fechaemisionfactura = fechaemisionfactura;
       this.status = status;
       this.facturadetalles = facturadetalles;
    }
   
    public Integer getIdfacturacabecera() {
        return this.idfacturacabecera;
    }
    
    public void setIdfacturacabecera(Integer idfacturacabecera) {
        this.idfacturacabecera = idfacturacabecera;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Empresacliente getEmpresacliente() {
        return this.empresacliente;
    }
    
    public void setEmpresacliente(Empresacliente empresacliente) {
        this.empresacliente = empresacliente;
    }
    public String getCorrelativofactura() {
        return this.correlativofactura;
    }
    
    public void setCorrelativofactura(String correlativofactura) {
        this.correlativofactura = correlativofactura;
    }
    public String getNumerofactura() {
        return this.numerofactura;
    }
    
    public void setNumerofactura(String numerofactura) {
        this.numerofactura = numerofactura;
    }
    public Date getFechaemisionfactura() {
        return this.fechaemisionfactura;
    }
    
    public void setFechaemisionfactura(Date fechaemisionfactura) {
        this.fechaemisionfactura = fechaemisionfactura;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getFacturadetalles() {
        return this.facturadetalles;
    }
    
    public void setFacturadetalles(Set facturadetalles) {
        this.facturadetalles = facturadetalles;
    }




}


