package farmacia.hibernate.modelo;
// Generated Oct 25, 2018 3:35:34 PM by Hibernate Tools 4.3.1



/**
 * Facturadetalle generated by hbm2java
 */
public class Facturadetalle  implements java.io.Serializable {


     private Integer idfacturadetalle;
     private Facturacabecera facturacabecera;
     private Producto producto;
     private double cantidad;
     private double subtotal;
     private boolean status;

    public Facturadetalle() {
    }

    public Facturadetalle(Facturacabecera facturacabecera, Producto producto, double cantidad, double subtotal, boolean status) {
       this.facturacabecera = facturacabecera;
       this.producto = producto;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
       this.status = status;
    }
   
    public Integer getIdfacturadetalle() {
        return this.idfacturadetalle;
    }
    
    public void setIdfacturadetalle(Integer idfacturadetalle) {
        this.idfacturadetalle = idfacturadetalle;
    }
    public Facturacabecera getFacturacabecera() {
        return this.facturacabecera;
    }
    
    public void setFacturacabecera(Facturacabecera facturacabecera) {
        this.facturacabecera = facturacabecera;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


