package farmacia.hibernate.modelo;
// Generated Oct 25, 2018 3:35:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idpersona;
     private String nombre;
     private String appaterno;
     private String apmaterno;
     private String numerodni;
     private Integer personaedad;
     private String direccion;
     private String telefono;
     private boolean status;
     private Set empleados = new HashSet(0);
     private Set personaclientes = new HashSet(0);

    public Persona() {
    }

	
    public Persona(String nombre, String appaterno, String apmaterno, String numerodni, boolean status) {
        this.nombre = nombre;
        this.appaterno = appaterno;
        this.apmaterno = apmaterno;
        this.numerodni = numerodni;
        this.status = status;
    }
    public Persona(String nombre, String appaterno, String apmaterno, String numerodni, Integer personaedad, String direccion, String telefono, boolean status, Set empleados, Set personaclientes) {
       this.nombre = nombre;
       this.appaterno = appaterno;
       this.apmaterno = apmaterno;
       this.numerodni = numerodni;
       this.personaedad = personaedad;
       this.direccion = direccion;
       this.telefono = telefono;
       this.status = status;
       this.empleados = empleados;
       this.personaclientes = personaclientes;
    }
   
    public Integer getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(Integer idpersona) {
        this.idpersona = idpersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAppaterno() {
        return this.appaterno;
    }
    
    public void setAppaterno(String appaterno) {
        this.appaterno = appaterno;
    }
    public String getApmaterno() {
        return this.apmaterno;
    }
    
    public void setApmaterno(String apmaterno) {
        this.apmaterno = apmaterno;
    }
    public String getNumerodni() {
        return this.numerodni;
    }
    
    public void setNumerodni(String numerodni) {
        this.numerodni = numerodni;
    }
    public Integer getPersonaedad() {
        return this.personaedad;
    }
    
    public void setPersonaedad(Integer personaedad) {
        this.personaedad = personaedad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getPersonaclientes() {
        return this.personaclientes;
    }
    
    public void setPersonaclientes(Set personaclientes) {
        this.personaclientes = personaclientes;
    }




}


