package farmacia.hibernate.modelo;
// Generated Oct 25, 2018 3:35:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personacliente generated by hbm2java
 */
public class Personacliente  implements java.io.Serializable {


     private Integer idpersonacliente;
     private Persona persona;
     private boolean status;
     private Set boletacabeceras = new HashSet(0);

    public Personacliente() {
    }

	
    public Personacliente(Persona persona, boolean status) {
        this.persona = persona;
        this.status = status;
    }
    public Personacliente(Persona persona, boolean status, Set boletacabeceras) {
       this.persona = persona;
       this.status = status;
       this.boletacabeceras = boletacabeceras;
    }
   
    public Integer getIdpersonacliente() {
        return this.idpersonacliente;
    }
    
    public void setIdpersonacliente(Integer idpersonacliente) {
        this.idpersonacliente = idpersonacliente;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getBoletacabeceras() {
        return this.boletacabeceras;
    }
    
    public void setBoletacabeceras(Set boletacabeceras) {
        this.boletacabeceras = boletacabeceras;
    }




}


