package farmacia.hibernate.modelo;
// Generated Oct 25, 2018 3:35:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idproducto;
     private String nombreproducto;
     private String descripcionproducto;
     private String dosisproducto;
     private double precioventa;
     private double igv;
     private double preciofinal;
     private int stock;
     private boolean status;
     private Set boletadetalles = new HashSet(0);
     private Set productodescuentos = new HashSet(0);
     private Set facturadetalles = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String nombreproducto, String descripcionproducto, String dosisproducto, double precioventa, double igv, double preciofinal, int stock, boolean status) {
        this.nombreproducto = nombreproducto;
        this.descripcionproducto = descripcionproducto;
        this.dosisproducto = dosisproducto;
        this.precioventa = precioventa;
        this.igv = igv;
        this.preciofinal = preciofinal;
        this.stock = stock;
        this.status = status;
    }
    public Producto(String nombreproducto, String descripcionproducto, String dosisproducto, double precioventa, double igv, double preciofinal, int stock, boolean status, Set boletadetalles, Set productodescuentos, Set facturadetalles) {
       this.nombreproducto = nombreproducto;
       this.descripcionproducto = descripcionproducto;
       this.dosisproducto = dosisproducto;
       this.precioventa = precioventa;
       this.igv = igv;
       this.preciofinal = preciofinal;
       this.stock = stock;
       this.status = status;
       this.boletadetalles = boletadetalles;
       this.productodescuentos = productodescuentos;
       this.facturadetalles = facturadetalles;
    }
   
    public Integer getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }
    public String getNombreproducto() {
        return this.nombreproducto;
    }
    
    public void setNombreproducto(String nombreproducto) {
        this.nombreproducto = nombreproducto;
    }
    public String getDescripcionproducto() {
        return this.descripcionproducto;
    }
    
    public void setDescripcionproducto(String descripcionproducto) {
        this.descripcionproducto = descripcionproducto;
    }
    public String getDosisproducto() {
        return this.dosisproducto;
    }
    
    public void setDosisproducto(String dosisproducto) {
        this.dosisproducto = dosisproducto;
    }
    public double getPrecioventa() {
        return this.precioventa;
    }
    
    public void setPrecioventa(double precioventa) {
        this.precioventa = precioventa;
    }
    public double getIgv() {
        return this.igv;
    }
    
    public void setIgv(double igv) {
        this.igv = igv;
    }
    public double getPreciofinal() {
        return this.preciofinal;
    }
    
    public void setPreciofinal(double preciofinal) {
        this.preciofinal = preciofinal;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getBoletadetalles() {
        return this.boletadetalles;
    }
    
    public void setBoletadetalles(Set boletadetalles) {
        this.boletadetalles = boletadetalles;
    }
    public Set getProductodescuentos() {
        return this.productodescuentos;
    }
    
    public void setProductodescuentos(Set productodescuentos) {
        this.productodescuentos = productodescuentos;
    }
    public Set getFacturadetalles() {
        return this.facturadetalles;
    }
    
    public void setFacturadetalles(Set facturadetalles) {
        this.facturadetalles = facturadetalles;
    }




}


